#!/bin/bash

ARTIFACTORY_URL='https://artifacts.horizon.dif.bankofamerica.com/artifactory'
API_ENDPOINT='/api/repositories?type=local'

# Fetching repository keys from Artifactory API
repo_keys=$(curl -s -u admin "${ARTIFACTORY_URL}${API_ENDPOINT}" | jq -r '.[].key')

# Iterate through each repository key and execute the curl command
for repo_key in $repo_keys; do
  curl -X POST -u admin "${ARTIFACTORY_URL}/api/federation/migrate/${repo_key}"
done
